### ISSUE TITLE
Modal: do not render the close button on fullContent

### ISSUE THREAD

**Issue by franckgaudin** [gsoft-inc/ov-igloo-ui#314]
### What happened?

The header of the modal is automatically set to display none when the `fullContent` option is chosen. In some cases we want to display the close button.

### Example

![modal-close-btn](https://user-images.githubusercontent.com/2379339/212980622-1b637dfb-a076-4d71-a6df-cb17d8432860.png)

### Component

Modal

### Component Version

latest

**Comment by vicky-comeau** [comment]
The close button is now displayed when isClosable and fullContent are true.
