### ISSUE TITLE
Feature Request: Add new props ref and autofocus on Textarea

### ISSUE THREAD

**Issue by franckgaudin** [gsoft-inc/ov-igloo-ui#328]
### Component that this feature request involves

Textarea

### Is your feature request related to a problem? Please describe

For the form I'm working on, the textarea also takes a ref and an autofocus, which are not in the igloo component at the moment.

> send by Kevin Paul (Uzinakod) on slack

### Describe the solution you'd like

Add new props for the `ref` and the `autofocus`

**Comment by vicky-comeau** [comment]
This has been completed
