### ISSUE TITLE
[Feature Request]: Remove the necessity to write <Toaster toasts={toastList} /> each time we want a toaster

### ISSUE THREAD

**Issue by CarolineSabourin-Jean** [gsoft-inc/ov-igloo-ui#364]
### Component that this feature request involves

Toaster

### Is your feature request related to a problem? Please describe

We have to write <Toaster toasts={toastList} /> each time we want to use a toaster. 

### Describe the solution you'd like

It would be nice if we can only write <Toaster toasts={toastList} /> one time at the root of the app, and after, we only have to use toast.error/success when we need a toaster. As a reference, you can see in portal what has been done with the toaster component.

**Comment by vicky-comeau** [comment]
This has been completed :)

**Comment by CarolineSabourin-Jean** [comment]
Thanks!
