### ISSUE TITLE
[Bug]: Can surpass maxLength in Textarea with an emoji, leading to negative character indicator

### ISSUE THREAD

**Issue by Ignotos** [gsoft-inc/ov-igloo-ui#366]
### Contact Details

michael.ignoto@gsoft.com

### What happened?

Steps to reproduce:

1. Write until the character indicator shows 1
2. Add an emoji

![Textarea-emoji-bug](https://user-images.githubusercontent.com/15761411/225738426-9e57ba5b-433c-4cc3-94f2-57447d983107.gif)

Result: We surpass the maxLength specified and the character indicator shows a negative number

### Component

Textarea

### Component Version

0.1.5

### Which browsers are you seeing the problem on?

Chrome

**Comment by jgclement91** [comment]
Another related issue is that even though the text area is in an error state, is doesn't displays the expected error state as documented in Storybook

**Comment by franckgaudin** [comment]
@jgclement91 I don't quite understand the issue you are talking about, do you have a screen shot so I can visualize the problem.

**Comment by franckgaudin** [comment]
We have just released a [fix](https://www.npmjs.com/package/@igloo-ui/textarea) that makes it impossible to add an emoji when there is only one character left, so this should not happen again.

Regarding the rendering of the error, the component does not handle logic, it only handles the rendering. To display an error, the parent must pass it the `error: true` props;

**Comment by jgclement91** [comment]
Great! 
I didn't realize that the validation message was from built-in input validation
