### ISSUE TITLE
[Bug] ActionMenu Component breaks when used within a modal with scrollwheel

### ISSUE THREAD

**Issue by JeffreyLYT** [gsoft-inc/ov-igloo-ui#370]
Contact Details
jeffrey.lam@gsoft.com

What happened?
Using component code out of the box inside modal component with a scrollwheel causes dropdown to bug

![KebabLastCommentBug](https://user-images.githubusercontent.com/43586477/226440129-1351c15d-623f-42c7-9ace-c00e761a4a84.gif)

Result: Dropdown overflows outside the parent component

Component
AcrtionMenu

Component Version
0.1.2

Which browsers are you seeing the problem on?
Chrome

**Comment by franckgaudin** [comment]
Thanks @JeffreyLYT , we will add it to our backlog and work on the bug quickly.
