### ISSUE TITLE
[Bug]: When dismissing a Dialog (or other similar component) displayed on top of a Modal, the Modal is also dismissed

### ISSUE THREAD

**Issue by Ignotos** [gsoft-inc/ov-igloo-ui#377]
### Contact Details

michael.ignoto@gsoft.com

### What happened?

When a Dialog (or other similar type of component) is displayed on top of a Modal with isDismissable, when the Dialog is dismissed, the Modal below is also dismissed even though we would expect it not to.  

### Component

Modal

### Component Version

1.2.2

### Which browsers are you seeing the problem on?

Chrome

**Comment by franckgaudin** [comment]
This issue has already been reported to us in the past. To solve this situation, you will find a workaround in the documentation. Here is the [link](https://igloo.officevibe.design/component/Dialog#troubleshooting) explaining what to do.
