### ISSUE TITLE
[Bug]: The ActionMenu is not the same as in Figma

### ISSUE THREAD

**Issue by CarolineSabourin-Jean** [gsoft-inc/ov-igloo-ui#399]
### What happened?

There should be no hover state on another item when hovering a disabled item (from https://igloo.officevibe.design/storybook/?path=/docs/components-actionmenu--docs):
![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/25105785/ba494d8a-927b-493d-848e-88b40d1516cd)

Linked to the previous point, there should be no hover state when nothing is hovered (from https://igloo.officevibe.design/storybook/?path=/docs/components-actionmenu--docs):
![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/25105785/32f4396c-6789-4107-87ab-7cb2f8494794)

Also, there should be some spacing here (spacing from figma):
![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/25105785/614cb9c8-e9bb-4859-87ed-a418775466b1)

Also, the icon is not the right color (color from figma):
![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/25105785/3dd1c530-1c4b-4205-bf5b-20f2edcf0e83)

Also, I was expecting to see the ActionMenu move if his reference is moving (see behaviour of the legacy actionMenu):
![LegacyActionMenu](https://github.com/gsoft-inc/ov-igloo-ui/assets/25105785/de3eb87b-583c-40eb-b022-939c682964ba)
And the Igloo ActionMenu:
![IglooActionMenu](https://github.com/gsoft-inc/ov-igloo-ui/assets/25105785/a6d647fa-6ff0-424e-ab67-cd37ea5470e1)

And as my last point, I think I could be a lot easier to use the component if the ActionMenuOption was an object
`{
    label: string,
    icon: node,
    onClick: func,
    closeMenuOnClick: bool,
    disabled: bool
}`
As of today, we need to have a value and always do a switch/case on that value for the closeOnSelect and onOptionSelect. It becomes less readable in my opinion.

### Component

ActionMenu

### Component Version

0.1.2

**Comment by franckgaudin** [comment]
Thanks for the feedback @CarolineSabourin-Jean we will add it to the roadmap and make the necessary corrections.

**Comment by CarolineSabourin-Jean** [comment]
Perfect, thanks!
