### ISSUE TITLE
[Bugs]: TagPicker missing error prop, focused on page load, missing ability to provide icon 

### ISSUE THREAD

**Issue by Ignotos** [gsoft-inc/ov-igloo-ui#410]
### What happened?

1. The TagPicker is missing an error prop in order to display the error state (like Input, Textarea, Datepicker have) 
2. The TagPicker is focused on initial load. This can be seen for example in the [storybook for the component](https://igloo.officevibe.design/storybook/?path=/docs/components-tagpicker--docs), the last picker on the page is focused (it should not be focused by default on initial load or the focus should be configurable) 
3. In our mockups, we have a magnifying glass icon that should be there when nothing is selected in the picker, we would need a way to prepend an icon to the picker

### Component

TagPicker

### Component Version

0.1.4

### Which browsers are you seeing the problem on?

Chrome

**Comment by vicky-comeau** [comment]
Completed :)
