### ISSUE TITLE
[Bug]: TagPicker item error state is not working

### ISSUE THREAD

**Issue by CarolineSabourin-Jean** [gsoft-inc/ov-igloo-ui#450]
### What happened?

When I set hasError on a TagPicker selectedResults item, there's no red border : 
![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/25105785/74a285bb-71d9-42e8-87ef-bf29d3d49213)

Also, when the TagPicker with error prop set to true isFocused, the border is blue instead of red : 
![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/25105785/08713881-cd83-49a4-9f9e-d39dfdc127f2)

### Component

TagPicker

### Component Version

0.3.0

**Comment by franckgaudin** [comment]
We'll add this issue to our backlog and prioritize it. 

As far as the focus behavior is concerned, this is what is expected during a focus. Our input components all work on the same principle.

**Comment by CarolineSabourin-Jean** [comment]
Thanks!

Ok for the focus + error state. I've just found it weird to have a red error message but a blue border :P No problem if it is as designed!
