### ISSUE TITLE
[Feature Request]: Add a prop onAfterClose on the ActionMenu

### ISSUE THREAD

**Issue by CarolineSabourin-Jean** [gsoft-inc/ov-igloo-ui#457]
### Component that this feature request involves

ActionMenu

### Is your feature request related to a problem? Please describe

I need to remove a css class onClose of the ActionMenu, but it is not visually nice because of the animation (the onClose is triggered before the animation is completed). With a prop onAfterClose triggered after the animation is completed, it would be perfect for my case! Now I use a settimeout and the timeout value is 150 because I checked in the ds code to see what it is. So if you change it, my value will not be good anymore. The best would be a onAfterClose prop! Thanks!

### Describe the solution you'd like

Add a prop onAfterClose (or the naming that you want) on the ActionMenu that will be triggered after the animation is completed.

### Describe alternatives you've considered

As mentionned before, I used a settimeout, but it is not a good solution in my opinion.

**Comment by vicky-comeau** [comment]
This is completed.

**Comment by CarolineSabourin-Jean** [comment]
Cool thanks!
