### ISSUE TITLE
[Feature Request]: Allow subtitle to be a ReactNode in Dialog

### ISSUE THREAD

**Issue by jgclement91** [gsoft-inc/ov-igloo-ui#458]
### Component that this feature request involves

Dialog

### Is your feature request related to a problem? Please describe

We need to the Dialog's subtitle to allow having multiple paragraphs but for the moment, it only allows string.

### Describe the solution you'd like

Could the type for subtitle be string **or** ReactNode?

### Describe alternatives you've considered

For the moment, we will most likely be able to use a workaround but it won't follow our conventions.

### Additional context

![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/8974093/369f5947-6203-4070-83b3-fbd3a8199cc1)

Thanks!

**Comment by vicky-comeau** [comment]
This has been completed.
