### ISSUE TITLE
[Bug]: It is possible to add more than the maxTags tags in the TagPicker

### ISSUE THREAD

**Issue by CarolineSabourin-Jean** [gsoft-inc/ov-igloo-ui#460]
### What happened?

When we already have selectedResults (so the first render of the TagPicker has selectedResults), it is possible to add more tags in the TagPicker than the maxTags prop. For exemple, I want a max of 5 tags. When my TagPicker is empty at the first render, I can put max 5 tags. But when my selectedResults contain already 2 tags at the first render, I can now have 7 tags (and I don't want it).
![Démo](https://github.com/gsoft-inc/ov-igloo-ui/assets/25105785/1dcabda8-241b-4647-9691-1dd4c1b497be)

### Component

TagPicker

### Component Version

0.3.1

**Comment by vicky-comeau** [comment]
This is fixed and available now.
