### ISSUE TITLE
[Feature Request]: add onSearch and searchLatency props to Combobox

### ISSUE THREAD

**Issue by khashayartdfh** [gsoft-inc/ov-igloo-ui#472]
### Component that this feature request involves

combobox

### Is your feature request related to a problem? Please describe

Sometimes the list of options is too long to load at once. Calling the database for the auto-complete results as the user types would help.

### Describe the solution you'd like

With onSearch, we could have a callback that is triggered every time a keyup event happens (i.e. a character is added to or removed from the auto-complete search term). Using searchLatency, we'd be able to decide how often the callback is triggered. So for instance, if I have searchLatency set to 3, every time 3 characters are changed in the search term, the onSearch callback is triggered.

### Describe alternatives you've considered

Right now a custom wrapper is created around the existing component to handle this.

**Comment by JGpGH** [comment]
Loadash Debounce function or some equivalent could be useful to avoid spaming the event when typping

**Comment by vicky-comeau** [comment]
This has been merged.
