### ISSUE TITLE
[Feature Request]: Add infinite scroll capabilities to combobox 

### ISSUE THREAD

**Issue by JGpGH** [gsoft-inc/ov-igloo-ui#477]
### Component that this feature request involves

combobox

### Is your feature request related to a problem? Please describe

When we don't want to load all options at once because there's too much

### Describe the solution you'd like

An optional infinite scroll feature would allow us to iterate through a big list without having to load all results at once and load more results as needed.

### Describe alternatives you've considered

A custom component was made instead, calling a LoadMore(...) if it HasMore(...) when the user gets near the end of options.

**Comment by vicky-comeau** [comment]
Some one else requested this feature as well. I will add a callback like 'onScrollEnd', this way you can easily add more results if this happens.

**Comment by khashayartdfh** [comment]
Would be nice to have a `threshold` prop too so the user doesn't have to get to the very end for the callback to trigger. Specially if the function takes some time to execute.

`threshold` could be based on the last item visible using intersection observer. So if threshold is set to 6, when the 6th-from-last option becomes fully visible, the callback is triggered.

Alternatively, it could be based on scroll position. Let's say we split the scroll height of the options list into 2 sections and pass a fraction of the last half as the point where the callback is triggered. So if `threshold` is 0.75, then when the user scrolls to ~87 percent of the way down (i.e 0.75 x 0.5 + 0.5 = 0.875), the callback is triggered. With this option, the prop can have a default value of 1 so if you don't set it, the user has to scroll all the way down for the callback to trigger (i.e. 1 x 0.5 + 0.5 = 1)

Based on the threshold you set, you can also make sure you're loading a sensible number of additional options when `onScrollEnd` is triggered.

**Comment by vicky-comeau** [comment]
yes that's a good idea, I ended up adding this prop :) I looked at what you normally use in OV and I went with setting the number of pixels left at the end of the dropdown. 
I did look into the intersection observer as an option. I think it's fairly well supported. If you feel this is a better option, I could switch to it.

**Comment by vicky-comeau** [comment]
This has been completed.
