### ISSUE TITLE
[Feature Request]: We need to have a loading state for dialog component when clicking on validate button 

### ISSUE THREAD

**Issue by sbaboot** [gsoft-inc/ov-igloo-ui#486]
### Component that this feature request involves

Dialog

### Is your feature request related to a problem? Please describe

When I click on validate button, a call is made on the backend. It could be better to have a loading spinner during this call

### Describe the solution you'd like

Add a loading state on validate button

**Comment by vicky-comeau** [comment]
Hi, just to let you know that this is currently in progress and I have pinned the JIRA issue.

**Comment by vicky-comeau** [comment]
This has been completed. You can use the "loading" prop. There is also a new story in storybook to show you an example.
