### ISSUE TITLE
[Bug]: Modal 1.4.0 "X" button overlap with modal content

### ISSUE THREAD

**Issue by LaurentDavidD** [gsoft-inc/ov-igloo-ui#568]
### Contact Details

laurent.deschambault@workleap.com

### What happened?

After updating the modal from 1.3.3 to 1.4.0 we encountered an issue where the X button overlap with the modal content.

Modal 1.3.3

![modal_1 3 3](https://github.com/gsoft-inc/ov-igloo-ui/assets/129109443/5247430b-6232-4f5c-bd1d-a0a87a75e220)

Modal 1.4.0

![modal_1 4 0](https://github.com/gsoft-inc/ov-igloo-ui/assets/129109443/daf844d0-8d44-48af-a20b-403f19930286)

### Component

@igloo-ui/modal

### Component Version

1.4.0

### Which browsers are you seeing the problem on?

Chrome

**Comment by fraincs** [comment]
Fixed in 1.4.1
