### ISSUE TITLE
[Bug]: AreaChart - Empty tooltip when score is null

### ISSUE THREAD

**Issue by LaurentDario** [gsoft-inc/ov-igloo-ui#579]
### Contact Details

laurent.jouanneau@gsoft.com

### What happened?

When an AreaChart has data entries with a `null` score, it displays a dashed line instead of the solid blue line, but it still displays an empty tooltip. It would be probably better to disable the tooltip on data points that have no valid score.
![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/234418/c8c8b15c-819c-4f68-9431-d4932fb2d4a1)

### Component

AreaChart

### Component Version

1.0.1

### Which browsers are you seeing the problem on?

Chrome

**Comment by vicky-comeau** [comment]
This is the purpose of the **unavailableDataMessage** prop. Did you enter a value in here?

**Comment by LaurentDario** [comment]
You're right, that does the trick! Thank you. I thought it was for the empty state when no data is available at all only
