### ISSUE TITLE
[Bug]: TagPicker - Listbox is missing workleap rebranding

### ISSUE THREAD

**Issue by vicky-comeau** [gsoft-inc/ov-igloo-ui#595]
### What happened?

TagPicker is not using the common List component, therefore, it needs rebranding.
What is looks like now:
![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/110498164/948a6c83-601f-40ed-b6ba-5af0dfcab7fe)
I expect it to use this design:
https://www.figma.com/file/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?type=design&node-id=12%3A313&mode=dev
We originally followed the xsmall size, but it should actually be the small size.

### Component

TagPicker

### Component Version

latest

**Comment by fraincs** [comment]
Should the input trigger also follow Workleap Input design? The way it is right now it's not.

![Uploading image.png…]()
