### ISSUE TITLE
[Bug]: On chrome, the TagPicker remove button has a minor visual glitch

### ISSUE THREAD

**Issue by jgclement91** [gsoft-inc/ov-igloo-ui#605]
### Contact Details

julien.clement@gsoft.com

### What happened?

Here's a screenshot from Storybook.
It's on Chrome, with the zoom at 100% (so no zoom). It looks ok when zoomed at 110%.
Not happening on Firefox

![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/8974093/331642b1-5ffa-46ed-a386-d1962c5ae63d)

Thanks!

### Component

TagPicker

### Component Version

0.6.2

### Which browsers are you seeing the problem on?

Chrome

**Comment by vicky-comeau** [comment]
We updated the X icon and I don't seem to see this issue anymore.
