### ISSUE TITLE
[Bug]: The Select component's right arrow is too much on the right

### ISSUE THREAD

**Issue by CarolineSabourin-Jean** [gsoft-inc/ov-igloo-ui#652]
### What happened?

According to Figma, the right arrow is supposed to be a little bit more on the left:
![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/25105785/8c1676b8-3da4-47a3-93ea-38e2511dc340)

Current Select's right arrow:
![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/25105785/1a6b0798-85ac-41b9-9dc8-75bf0b828f38)

### Component

Select

### Component Version

1.3.13

**Comment by vicky-comeau** [comment]
We should probably update the icon while we're at it, too.
