### ISSUE TITLE
[Bug]: Dialog's validate button should fit-content when text is too long for the length of the button

### ISSUE THREAD

**Issue by CarolineSabourin-Jean** [gsoft-inc/ov-igloo-ui#663]
### What happened?

According to designers, when the validateText is longer than the width of the button (it happens "often" in french), the button should expand. The css to use is `min-width: fit-content;` on the ".ids-dialog__validate-btn".
![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/25105785/263766d6-76e7-442d-8639-95ea4117367d)

Instead of :
![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/25105785/caec8e7f-53c3-4c24-aa5c-dc2883fd03c1)

### Component

Dialog

### Component Version

0.8.0

**Comment by CarolineSabourin-Jean** [comment]
Ok perfect! Thanks!

**Comment by vicky-comeau** [comment]
This is completed :)

**Comment by CarolineSabourin-Jean** [comment]
Hi! I can see the issue is still there:
![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/25105785/6e3ac382-fdcb-4031-a360-7d69d9495b12)

**Comment by vicky-comeau** [comment]
it looks like it's still using version 0.8.4
The latest one is 0.8.5

**Comment by CarolineSabourin-Jean** [comment]
My screenshot is coming from storybook. So it is not the latest version on storybook?

**Comment by vicky-comeau** [comment]
It is, from storybook:
![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/110498164/cc6fe212-9594-4c16-a5fb-55ec29a4fe5e)

**Comment by CarolineSabourin-Jean** [comment]
In my opinion, yes it needs to be fixed on both, because the rebranding fs is not yet activated,

**Comment by vicky-comeau** [comment]
This should be fixed this time for the old brand as well.

**Comment by CarolineSabourin-Jean** [comment]
Cool thanks!
