### ISSUE TITLE
[Bug]: Rebranded Toggle has not the right css

### ISSUE THREAD

**Issue by CarolineSabourin-Jean** [gsoft-inc/ov-igloo-ui#710]
### What happened?

The rebranded Toggle component has not the right font-weight. See the Figma here : https://www.figma.com/file/zSpuR1wOAT99H6YfD29IRl/%F0%9F%90%B8-Hopper-Design-System?node-id=647%3A2549&mode=dev

Also, why is the ids-toggle taking 30px of height while the label is only taking 24px? It is problematic as it is introducing an unwanted "margin-bottom". 
![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/25105785/bd8350be-43e5-4114-8ac4-ef062b1790e6)
![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/25105785/19233673-df13-4df4-980f-c15dd548019a)

### Component

Toggle

### Component Version

1.2.0

**Comment by CarolineSabourin-Jean** [comment]
It is also missing a `flex-shrink: 0` on the `.ids-toggle__label:before` element :)

**Comment by vicky-comeau** [comment]
This has been fixed :)

**Comment by CarolineSabourin-Jean** [comment]
Cool thank you!
