### ISSUE TITLE
[Bug]: StackedBar border radius not applied correctly for items with zero value

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/ov-igloo-ui#716]
### What happened?

The radius in the StackedBar component is currently only being applied to the first and last items. However, this implementation leads to a scenario where, in cases of items with a value of 0, the radius is not visually represented as expected.

![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/38871812/5a996ee9-4e75-4876-ad6b-53756a454744)

### Component

StackedBar

### Component Version

latest

**Comment by fraincs** [comment]
Fixed in https://github.com/gsoft-inc/ov-igloo-ui/pull/725
