### ISSUE TITLE
[Bug]: I need to have a checked + disabled state together for the OptionButton 

### ISSUE THREAD

**Issue by CarolineSabourin-Jean** [gsoft-inc/ov-igloo-ui#724]
### What happened?

I need to have a checked + disabled state together for the OptionButton. So I need a visual effect to let the user know which OptionButton is checked, even if it is disabled.
![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/25105785/00294588-0750-461e-8aa0-b6ed779cbc79)

I need it for the Igloo version and the Workleap version. 

### Component

OptionButton

### Component Version

0.2.1

**Comment by vicky-comeau** [comment]
Also done.

**Comment by CarolineSabourin-Jean** [comment]
Cool thanks!
