### ISSUE TITLE
[Bug]: The rebranded Tag's text is not centered

### ISSUE THREAD

**Issue by CarolineSabourin-Jean** [gsoft-inc/ov-igloo-ui#763]
### What happened?

From storybook:
![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/25105785/420b286f-ab69-4f9e-984c-8fb257394ad0)

The text is not well centered vertically.

### Component

Tag

### Component Version

1.5.4

**Comment by fraincs** [comment]
![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/361632/526a24e4-1ecd-4a29-8384-ca2d5b016f75)

The text is actually centered, that said it looks uncentered, this is a particularity of ABC Favorit, not one that we enjoy I should say. A fix for the whole font is planned. I'll wait for a designer input to see to which extent this if we fix this particular case or wait for a fix that will fix "centering" issues.

**Comment by CarolineSabourin-Jean** [comment]
Ok thank you for the answer!
