### ISSUE TITLE
[Bug]: Metric component - icon and box-shadow fix

### ISSUE THREAD

**Issue by JeffreyLYT** [gsoft-inc/ov-igloo-ui#787]
### Contact Details

jeffrey.lam@gsoft.com

### What happened?

There seems to be a mismtach between the component design and igloo
Notably, the icon should be bigger and there should be a slight box-shadow to the metric tile

https://www.figma.com/file/KXrVZlFqD8mmlxJJhL5Jhn/%E2%9D%84%EF%B8%8F-Igloo-Design-System?type=design&node-id=4051-2&mode=dev

Prod:
![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/43586477/0dcbe294-3e42-4be6-b61c-ff9461ad7fa9)
Design:
![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/43586477/a9dcdc83-c5be-4a02-b177-848ea96a59d7)

### Component

Metric

### Component Version

0.3.3

### Which browsers are you seeing the problem on?

Chrome

**Comment by fraincs** [comment]
The box shadow applied is the raised one, like in Figma, this won't be fixed. As for the arrow I am fixing this.
