### ISSUE TITLE
[Bug]: Incorrect color for the Secondary Ghost button text in Workleap's mode.

### ISSUE THREAD

**Issue by romanzhyn-workleap** [gsoft-inc/ov-igloo-ui#832]
### Contact Details

roman.zhyn@gsoft.com

### What happened?

The button component has incorrect text color in the default state for secondary/ghost appearance in the Workleap's mode. The correct token should be `--hop-neutral-text-weak` (#6C6C6B), but at the moment it is using `--ids-btn-text-ghost-secondary` which resolves into `--hop-neutral-text` (#3c3c3c).

|Result|
|---|
|**Design**|
| <img width="718" alt="image" src="https://github.com/user-attachments/assets/90ee2ad1-e0e1-425f-a7cf-b396ceb67eae"> |
|**Actual**|
 | <img width="547" alt="image" src="https://github.com/user-attachments/assets/e2698b19-56f8-4276-ac80-334ae59cb0d0">|

### Component

Button

### Component Version

0.9.1

### Which browsers are you seeing the problem on?

Chrome

**Comment by fraincs** [comment]
Thanks for the report, we had a card for this, this will be tackled soon.

**Comment by fraincs** [comment]
This has been fixed
